### ISSUE TITLE
upgrade heroku stacks from heroku 20 to heroku 22

### ISSUE THREAD

**Issue by kdinthehouse** [Mr-confused/catpack#53]
so ive been using catuser bot but recently my heroku stacks asking me to upgrade the stacks and I clicked update option and following message shows 

"heroku-22 will replace heroku-20 on the next deploy"

so I tried empty deploy and it still haven't changed. please help me with this
![photo_2022-06-28_02-14-58](https://user-images.githubusercontent.com/24727383/176032618-6bbcd4d4-01d7-4cc0-8682-e7380e579552.jpg)

**Comment by rahulps1000** [comment]
Connect your repo and manual deploy the app
It will be upgraded

**Comment by itsmepratheek** [comment]
> Connect your repo and manual deploy the app It will be upgraded

I tried that and I cant connect to github since the incident with heroku. and they saying github auth wont work for now
![Screenshot 2022-06-28 101430](https://user-images.githubusercontent.com/24727383/176094833-b8704a5f-96b1-4adf-9222-c94da935e315.png)

**Comment by rahulps1000** [comment]
This is fixed can you disconnect and reconnect from you heroku account settings

**Comment by Jisan09** [comment]
Just ignore,  u don't need to upgrade stack now.
We will provide details with next update, even if u did try to make stack 22 it will give error to u cz that python version you using isn't compatible with it.
& Now if u understand this im closing this issue

**Comment by itsmepratheek** [comment]
> This is fixed can you disconnect and reconnect from you heroku account settings

thanks for the info
